In [1]:
a='hello'

In [2]:
print(a)

hello


In [3]:
string1='hello'
string2="my friend"

string3="""welcome to all
in new day"""

print(string1)
print(string2)
print(string3)

hello
my friend
welcome to all
in new day


In [ ]:
name='gowrishankar'

address="""37, 4th street,
arasu colony,e.pudur,trichy-12."""

print(name)
print(address)


In [ ]:
name='gowri'
name1='shankr'
id(name), id(name1)


In [ ]:
id(a)

In [ ]:

a=10
b=20
print(id(a),id(b))

In [ ]:
#float doesnot show same value in id function
a=13.4
b=13.4
print(id(a),id(b))

In [ ]:
#precision problems in floats
c=.1+.1+.1-.3
print(c)

In [ ]:
#precision vs accuracy tradeoff

from decimal import *
a=Decimal('0.1')
b=Decimal('0.3')

c=a+a+a-b
print (f"the result is {c}")

In [ ]:
pi=3.14
type(pi)

In [ ]:
#if , else, elif 
a=16

if(a%3==0 and a%5==0):
    print("frizz buzz")
elif(a%3==0):
    print("frizz")
elif(a%5==0):
    print("buzz")
else:
    print("none")

In [ ]:
#ternary operator
mark=100

result="pass" if(mark>50) else "fail"

print("mark= {}".format(mark))
print("result= {}".format(result))

In [ ]:
#swap
a=10
b=20
tmp=0

tmp=a
a=b
b=tmp

print(a,b)

In [ ]:
#find area of a triangle
b=10
h=10
c=(0.5 * b* h)
print(f"area of triangle{c}")

In [ ]:
a=10
b=0.621
miles=(a*b)
print(miles)

In [ ]:
#odd or even

a=5

value="odd" if(a%2==0) else "even"
print(value)

In [ ]:
#leap year 
a=1996
year="leap" if(a%4==0) else "not leap"
print(year)

In [ ]:
#positive or negative or zero
a=10
if(a>0):
    print("positive")
elif(a==0):
    print("zero")
else:
    print("negative")

    


In [ ]:
#loop

value=0

while(value<10):
    print(value)
    value=value+1


In [ ]:
password="gowri"
pwd=""

while pwd!=password:
    pwd=input("enter your password:")

print=("password correct!! \nwelcome")
    

In [ ]:
#for loop

days=['sun','mon','tue','wed','thu','fri','sat']

for a in days:
    print(a)

In [ ]:
list(range(20))

In [11]:
for x in range(0,10,2):
    print(x)
    

0
2
4
6
8


#multiples of 2 using range
for x in range(0,10,2):
    print(x)

In [9]:
#multiples of 5 using range staring from 10 and ending in 100
for x in range(0,20,3):
    print(x)

0
3
6
9
12
15
18


In [ ]:
type(n)

In [2]:
#first n multiples of 5 using a for loop
n=input("enter the number:")
n=int(n)
for x in range(0,n+1):
    print(x*5)

enter the number:2
0
5
10


In [ ]:
#enumerate
day=['sun','mon','tue','wed','thu','fri','sat']
for index,data in enumerate(day):
    print(f"{index} :::> {data}")

In [3]:
n="gowri"
for index,data in enumerate(n):
    print(f"{index}---> {data}")

0---> g
1---> o
2---> w
3---> r
4---> i


In [ ]:
password="gowri"
pwd=''
count=0

while pwd!=password:
    if count==5:
        break
        count +=1
        pwd=input(f"attempt {count}:enter your password:")

if (pwd==password):
    print("authorized... \nwelcome you")
else:
    print("wrong password")
                
    

In [ ]:
#break and continue
animals=['dog','cat','parrot','lion','tiger']
for animals in animals:
    if(animals=='fish'):
        continue
    
    if(animals=='parrot'):
        print("error !! exiting!!  we have a bird")
        break
    print(animals)
else:
    print("printed all animals")

In [ ]:
days=['sun','mon','tue','wed','thu','fri','sat']

for days in days:
    if(days=='sun'):
        print("SUNDAY")
        continue
    if(days=='mon'):
        print("i hate monday")
        continue
    if(days=='thu'):
        continue
        
    print(days)
                    

In [ ]:
#read two number print their quotient an remainder
a=int(input("enter first number:"))
b=int(input("enter secound number:"))
q=a/b
r=a%b
print(f"quotient:{q}")
print(f"remainder:{r}")

In [ ]:
#factorial n number
n=int(input("enrer the number:"))
fact=1
i=1
while(i<n+1):
    fact=fact*i
    i=i+1
print(fact)

In [ ]:
a=int(input("enter the number:"))

while(a>0):
    x=a%10
    b=a/10
if(b==a):
    print("a is same number")
else:
    print("sum error occure")
print(x)


In [ ]:
x=int(input("enter the number:"))
for x in range(9,x,9):
    print(x)

In [ ]:
#swap variables
a=int(input("enter the number"))
b=int(input("enter the number"))

a=a^b
#b=a^b

print(a)
print(b)

In [5]:
#leap year
x=int(input("enter the number:"))
if(x%4==0 and x%100==0):
    print("leap year")
elif(x%400==0):
    print("not leap")

enter the number:1203


In [ ]:
#sum of all natural number
a=9
for b in range(1,a+1,1):
        print(b)
    

In [6]:
#leapyear in function

year=int(input("enter the year"));

def isleapyear(int year)
{
    istypicalleapyear(year) && not(isatypicalcommonyear(year);                            
}
def istypicalleapyear(int year)
{
    year % 4 == 0;
}
def isatypicalcommonyear(int year)
{
    year % 100 == 0 && not(year % 400 == 0);
}

SyntaxError: invalid syntax (<ipython-input-6-7437fb43f695>, line 5)

In [ ]:
#try catch
try:
    a=0/0
    f=open("hello.txt","r")
    print(r.read())
except:
    print("error in opening file")

In [ ]:
#try catch II
try:
    #a=0/0
    f=open("hello.txt","r")
    print(r.read())
except IOError:
    print("error in opeing file")
except:
    print("error")

In [ ]:
#USER INPUT
a=input("enter the value of a")
a

In [ ]:
#file handling 

f=open("fil.txt","w")
f.write("hi welcome, \n i am your friend")
f.close()

In [ ]:
f=open("fil.txt","r")
a=f.read()
f.close()
print(a)

In [ ]:
with open("fil.txt","r") as f:
    for line in f:
        print(line)

In [ ]:
f=open("fil.txt","r")
a=f.readlines()
f.close()
print(a)

In [ ]:
with open("fil.txt","r")as f:
    for i,line in enumerate(f):
        print(i,line)

In [ ]:
f=open("fil.txt","a")
a=f.write("welcome too all")
f.close()
print(a)

In [ ]:
import csv
filename="tweets_withheader.csv"
with open(filename,"r")as f:
    data_reader=csv.reader(f,delimiter=',')
    headers=next(data_reader)
    print("headers = "+ str(headers))
    
    print("\nContent")
    for line in data_reader:
        print(line)
    
    

In [ ]:
import csv
filename="tweets_noheader.csv"
with open(filename,"r")as f:
    data_reader=csv.reader(f,delimiter=',')
    
    
    print("Content")
    for line in data_reader:
        print(line)
    
    

In [ ]:
#json

import json
filename="moviereview.json"
with open(filename,"r")as f:
    a=f.read()
    movie=json.loads(a)
movie


In [ ]:
import json
filename="moviereview.json"
with open(filename,"r")as f:
    movie=json.load(f)
movie

In [ ]:
movie['Year']

In [ ]:
import json
filename="moviereviews.jsonl"
with open(filename,"r")as f:
    for  line in f:
        movie=json.loads(line)
        print(movie)

In [ ]:
#input 
a=int(input("enter the a"))
b=int(input("enter the b"))

while(b==0):
    try:
        a/b
    except:
        print("cannot divid zero")
        b=int(input("enter the b"))

c=a/b
print(c)


In [ ]:
#list comprehensions

squares=[]
for x in range(10):
    squares.append(x*x)
squares

In [ ]:
#type II
squares=[x**2 for x in range(10)]
squares

In [ ]:
#type III
squares=[x*x for x in range(10)]
squares

In [ ]:
combos=[]

for x in [1,2,3]:
    for y in [1,2,3]:
        if x!=y:
            combos.append((x,y))
            
combos

In [ ]:
combos=[(x,y) for x in [1,2,3] for y in [1,2,3]]
combos

In [ ]:
combos=[(x,y) for x in [1,2,3] for y in [1,2,3] if x!=y]
combos

In [ ]:
combos=[(x,y) for x in [1,2,3]
      for y in [1,2,3]
      if x!=y]
combos

In [ ]:
combos=[(x,y) if x!=y else (0,0)
       for x in [1,2,3]
       for y in [1,2,3]]
combos

In [ ]:
x=[111,222,333,444,555,666,777,888,999,777]
x

In [ ]:
#given number in squres and cube
import random
a=[random.randint(100,999) for _ in range(10)]
[(i,i**2,i**3)for i in a]

In [ ]:
x=int(input("enter 3 digit number:"));
print(x)
squares=[x*x]
squares
cube=[x**3]
cube
print(squares)
print(cube)

In [ ]:
#dictionaryy comprehesion
fords=("the quick brown fox jumped over the lazy dog")
tokens=fords.split(',')
tokens


In [ ]:
word_len={}


for w in tokens:
    word_len[w]=len(w)
    
word_len

In [ ]:
word_len={w:len(w) for w in words.split()}
word_len

In [ ]:
#creating generators

squares=(x*x for x in range(10))
squares

In [ ]:
for item in squares:
    print(item)

In [ ]:
#sume fundamental programming concept
#map
def f(x):
    return x*x

n=range(10)

squares=map(f,n)

print(squares)
print(list(squares))

In [ ]:
def add(a,b):
    return a+b

a=[1,2,3]
b=[2,1,4]

results=map(add,a,b)
list(results)

In [ ]:
def add(a,b):
    return a+b

a=[1,2,3]
b=[1,2,3,4]

c=map(add,a,b)
list(c)

In [ ]:
##filter
def is_even(a):
    return a%2==0

seq=range(20)

evenNumbers=filter(is_even,seq)
list(evenNumbers)

In [ ]:
In

In [ ]:
Out

In [ ]:
#magic commands
%magic

In [ ]:
%magic

In [ ]:
from random import random

l=[int(random()*10) for _ in range(0,1000)]
t=[int(random()*10) for _ in range(0,1000)]
%time print(5 in l)
%time print(5 in t)



In [ ]:
%%time
l=[10,20,30]
print(5 in l)

In [ ]:
%timeit l=[10,20,30]
print(5 in l)

In [ ]:
%precision 2
l=[(random()*10) for _ in range(0,10)]
print(l)

In [ ]:
f=open("AliceInWonderland.txt")
tokens=
tokens

## numpy

In [4]:
import numpy as np

In [5]:
import numpy as np
print(np.__version__)

1.16.2


# creating a numpy arrays

In [6]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
a=np.array([1,2.2,3,4,5])
a

array([1. , 2.2, 3. , 4. , 5. ])

In [11]:
a=np.array([1,2,3,4,5])
newstrArry=a.astype(str)
newstrArry

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [12]:
help(a.astype)

Help on built-in function astype:

astype(...) method of numpy.ndarray instance
    a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
    
    Copy of the array, cast to a specified type.
    
    Parameters
    ----------
    dtype : str or dtype
        Typecode or data-type to which the array is cast.
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout order of the result.
        'C' means C order, 'F' means Fortran order, 'A'
        means 'F' order if all the arrays are Fortran contiguous,
        'C' order otherwise, and 'K' means as close to the
        order the array elements appear in memory as possible.
        Default is 'K'.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur. Defaults to 'unsafe'
        for backwards compatibility.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are al

In [14]:
newstrArry.tolist()

['1', '2', '3', '4', '5']

In [15]:
a=np.array([1,2,3,4,5],dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [16]:
#meta function
a.ndim, a.shape, a.size

(1, (5,), 5)

In [22]:
##create a 1-D nupy array of 50 elements and display its contents
a=np.array(range(50))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
##write a function meta that prints the dimension ,shape and size

def meta(a):
    print(a.ndim)
    print(a.shape)
    print(a.size)
meta(a)


1
(50,)
50


# new datatype object

In [23]:
a=np.array([1,"gowri",98.2])
a

array(['1', 'gowri', '98.2'], dtype='<U11')

In [24]:
a=np.array([1,"gowri",98.2],dtype=np.object)
a

array([1, 'gowri', 98.2], dtype=object)

# can handle vectorized operations

In [26]:
l=[1,2,3,4,5]
npa=np.array(l)
l,npa

([1, 2, 3, 4, 5], array([1, 2, 3, 4, 5]))

In [28]:
l+2

TypeError: can only concatenate list (not "int") to list

In [31]:
npa+2

array([3, 4, 5, 6, 7])

# multi dimensional arrays

In [32]:
b=np.array([[1,2,3,4,5],[6,7,8,9,0]])
b

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [33]:
b.ndim, b.shape, b.size, b.dtype

(2, (2, 5), 10, dtype('int32'))

# some helpful functions

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Return a new array 

In [39]:
np.empty((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# sequence generators

In [40]:
start=100
end=10
count=10
np.linspace(start,end,count)

array([100.,  90.,  80.,  70.,  60.,  50.,  40.,  30.,  20.,  10.])

In [41]:
start=0
end=10
step=2
np.arange(start,end,step)

array([0, 2, 4, 6, 8])

In [42]:
np.random.standard_normal((2,2))

array([[-0.67982017,  1.60187992],
       [-1.75094797, -0.04288133]])

In [43]:
a=np.random.standard_normal((2,3))
b=np.random.standard_normal((2,3))
a,b

(array([[ 1.28529271, -0.38346978, -0.4822614 ],
        [-1.31590394, -0.56280842, -0.44092106]]),
 array([[-0.38671501, -1.7662288 , -0.73725085],
        [-1.5260873 , -0.38141534,  0.11213967]]))

In [44]:
np.vstack([a,b])

array([[ 1.28529271, -0.38346978, -0.4822614 ],
       [-1.31590394, -0.56280842, -0.44092106],
       [-0.38671501, -1.7662288 , -0.73725085],
       [-1.5260873 , -0.38141534,  0.11213967]])

In [45]:
a.transpose()
a

array([[ 1.28529271, -0.38346978, -0.4822614 ],
       [-1.31590394, -0.56280842, -0.44092106]])

In [46]:
np.save('myfirstarray.npy',a)

In [47]:
al=np.load('myfirstarray.npy')
al

array([[ 1.28529271, -0.38346978, -0.4822614 ],
       [-1.31590394, -0.56280842, -0.44092106]])

In [48]:
a=[[1,2],[5,6]]
b=[[1,0],[0,1]]
np.dot(a,b)

array([[1, 2],
       [5, 6]])

In [49]:
import numpy as np

In [53]:
a=np.array(range(1,11))
b=np.array(range(2001,2011))
a,b

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010]))

In [54]:
a=np.zeros((3,3))
for row in range(3):
    for col in range(3):
        if(row==col):
            a[row][col]=1
        print(row,col,a[row][col])
a

0 0 1.0
0 1 0.0
0 2 0.0
1 0 0.0
1 1 1.0
1 2 0.0
2 0 0.0
2 1 0.0
2 2 1.0


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
##### input from user
row=int(input("enter the row"))
col=int(input("enter the col"))
b=np.empty((row,col))

for i in range(row):
    for j in range(col):
        b[i][j]=int(input("enter the row,col value"))
b

enter the row3
enter the col3
enter the row,col value1
enter the row,col value2
enter the row,col value3
enter the row,col value4
enter the row,col value5
enter the row,col value6
enter the row,col value7
enter the row,col value8
enter the row,col value9


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [58]:
#add two matrix
a=np.array([range(5),range(5,10),range(10,15),range(15,20)])
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# indexing and slicing

In [2]:
import numpy as np
v=np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [2]:
v[0],v[1],v[-1]

(0.0, 2.5, 10.0)

In [3]:
v[2:4]

array([5. , 7.5])

In [9]:
vv=np.random.random((5,5))
vv*10

array([[0.4947691 , 6.33473827, 3.28623422, 0.40974298, 0.72280819],
       [4.62582358, 4.40914114, 4.29031862, 8.65264403, 0.24076793],
       [2.71947401, 1.35680319, 1.72854478, 7.75434149, 2.4474315 ],
       [1.81241234, 9.95346507, 3.85194644, 9.90127582, 5.67046798],
       [7.95803782, 5.23853236, 2.43318065, 2.33623126, 4.85585992]])

In [5]:
vv[0][0]

0.19777368935183426

In [6]:
vv[0,0],vv[4,3]

(0.19777368935183426, 0.4768572486897926)

In [7]:
l1=[[1,2,3],[4,5,6]]
l1[0][1]

2

In [8]:
vv

NameError: name 'vv' is not defined

In [9]:
vv[2:5,1]

array([0.0404281 , 0.66348518, 0.62407846])

In [10]:
vv[2:5,0:3]

array([[0.26592713, 0.0404281 , 0.35707195],
       [0.84093468, 0.66348518, 0.02539135],
       [0.53502335, 0.62407846, 0.50445089]])

In [11]:
print(v)
v2=v[2:4]
print(v2)
v2[0]=55
print(v,v2)

[ 0.   2.5  5.   7.5 10. ]
[5.  7.5]
[ 0.   2.5 55.   7.5 10. ] [55.   7.5]


In [12]:
print(v)
v2=v[2:4].copy()
print(v2)
v2[0]=22
print(v,v2)

[ 0.   2.5 55.   7.5 10. ]
[55.   7.5]
[ 0.   2.5 55.   7.5 10. ] [22.   7.5]



# filtering data

In [3]:
print(v)
v1=v[[1,2,3]]
print(v1)

[ 0.   2.5  5.   7.5 10. ]
[2.5 5.  7.5]


In [4]:
v>1

array([False,  True,  True,  True,  True])

In [5]:
bool_ind=v>5

In [6]:
v[bool_ind]

array([ 7.5, 10. ])

In [10]:
print(vv)
vv[vv>.5]

[[0.04947691 0.63347383 0.32862342 0.0409743  0.07228082]
 [0.46258236 0.44091411 0.42903186 0.8652644  0.02407679]
 [0.2719474  0.13568032 0.17285448 0.77543415 0.24474315]
 [0.18124123 0.99534651 0.38519464 0.99012758 0.5670468 ]
 [0.79580378 0.52385324 0.24331806 0.23362313 0.48558599]]


array([0.63347383, 0.8652644 , 0.77543415, 0.99534651, 0.99012758,
       0.5670468 , 0.79580378, 0.52385324])

In [11]:
vv[vv>.5]=1
vv

array([[0.04947691, 1.        , 0.32862342, 0.0409743 , 0.07228082],
       [0.46258236, 0.44091411, 0.42903186, 1.        , 0.02407679],
       [0.2719474 , 0.13568032, 0.17285448, 1.        , 0.24474315],
       [0.18124123, 1.        , 0.38519464, 1.        , 1.        ],
       [1.        , 1.        , 0.24331806, 0.23362313, 0.48558599]])

In [ ]:
vals=np.arange(10)
#vals=np.array([1,3,5,7,9])
print(vals)
np.where(vals%3==0)

In [ ]:
vals_new=np.where(vals%2==0,-1,vals)
vals_new

In [ ]:
data=np.array([range(5),range(5,10),range(10,15),range(15,20)])
data

# HW

In [ ]:
##two input from user
row=int(input("enter the row"))
col=int(input("enter the col"))
b=np.empty((row,col))

for i in range(row):
    for j in range(col):
        b[i][j]=int(input("enter the row,col value"))
row=int(input("enter the row"))
col=int(input("enter the col"))
a=np.empty((row,col))

for i in range(row):
    for j in range(col):
        b[i][j]=int(input("enter the row,col value"))
a,b

In [ ]:
import numpy as np

In [ ]:
a=data[(data%2!=0)]
b=np.where(data%3==0,-1,data)
a,b

In [ ]:
#add two matrix
a=np.array([range(5),range(5,10),range(10,15),range(15,20)])
b=np.array([range(4),range(4,8),range(8,12),range(12,16),range(16,20)])
print(a,"=a")
print(b,"=b")
c=a.transpose()
print(c,"=c")
d=c.transpose()
print(d,"=d")
e=d==a
print(e)

In [ ]:
r=np.arange(0,100,3)
r[(r%2==0) | (r%9==0)] #multiple 2 and 9
#r[(r%2==0) & (r%9==0)]only multiple 2 and 9

r

In [ ]:
import csv

temp=[]

f="weather1week.csv"
with open(f,"r")as f:
    a=csv.reader(f,delimiter=';')

    print("start")
    for line in a:
       # print(line[5])
        temp.append(line[5])
temp
b=np.array([temp],dtype=float)
b  
f=b*(9/5)+32
f


In [ ]:
##age list and year
age=np.array([10,20,30,40,50,60,70,80,90,11])
for year in range(2010,2021):
    age=age+1
age

In [ ]:
##5x5 matrix largest number and smallest number
a=np.random.random((5,5))
a=a*10
a
n=a.astype(int)
n
x=n.max()
y=n.min()
print(x)
print(y)


In [ ]:
##create a numpy array of marks
a=np.random.randint(500,1200,size=20)
a
b=(a*100)/1200
print(b)
c=b.max()
print("first mark",c)
d=b.min()
print("last mark",d)

In [ ]:
#creat a numpy array 50 random elements
a=np.random.randint(50,size=50)
a
v=a.min()
print(v)
m=a.max()
print(m)
b=(a-v)/(m-v)
b
print("normalized value",b)

In [ ]:
##read the week file and find the average and hotter and cold 
import csv
temp=[]
f="weather1week.csv"
with open(f,"r")as f:
    r=csv.reader(f,delimiter=";")
    print("start")
    for line in r:

        temp.append(float(line[5]))
temp
a=np.array([temp])
b=np.mean(a)
print("average temperature",b)
c=a.max()
print("hottest temperature",c)
d=a.min()
print("coldest temperature",d)
e=a(a%24.19791)
e


In [ ]:
##reverse the string

a=input("enter the name")
print(a)


# some additional snippets

In [ ]:
import numpy as np
data=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float)
data

In [ ]:
data[:,1:4]

In [ ]:
data[::-1]

In [ ]:
data[:,::-1]

In [ ]:
data[::-1,::-1]

In [ ]:
data[0,0]=np.inf
data[-1,-1]=np.nan
data

In [ ]:
#reshaping
reshaped=data.reshape((5,2))
reshaped

In [ ]:
flattened=data.flatten()
flattened

In [ ]:
#random numbers
np.random.rand(3,3)


In [16]:
np.random.randint(0,10,(5,5))

array([[4, 4, 9, 1, 6],
       [2, 2, 2, 9, 3],
       [1, 3, 4, 8, 1],
       [0, 3, 4, 6, 6],
       [2, 3, 4, 7, 2]])

In [ ]:
np.random.choice(['India','China','Australia','Canada','France'],(3,4))

In [ ]:
np.random.seed(5)
np.random.choice(['India','China','Australia','Canada','France'],(3,4))

In [ ]:
#consider the set of students
names=["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o"]
chess=np.random.choice(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o"],(10,5))
print("chess=",chess)


# vectorize

In [ ]:
def calc(a):
        if a%2==0:
            return a**2
        else:
            return a-1

In [ ]:
vals=np.array([1,2,3,4,5])
calc(vals[0])

In [ ]:
calc(vals)

In [ ]:
v_calc=np.vectorize(calc)
v_calc(vals)

In [ ]:
b=np.array([1,2,3,4,5])
bin(b[3])

In [ ]:
v_bin=np.vectorize(bin)
v_bin(b)

# records-using heterogeneous datatypes

In [ ]:
rec=np.array([(1,(95.5,98),'ram'),(2,(100,96.5),'raj')],dtype=[('rollno',np.int32),('marks',np.float16,2),('names',np.str,4)])

In [ ]:
rec

In [ ]:
rec['names']

In [ ]:
rec[0]

In [ ]:
rec['names']

In [ ]:
rec[0]['marks']

In [ ]:
rec['marks'][0]

In [ ]:
schems=np.dtype([('year',np.float16),
                ('month',np.float16),
                ('day',np.float16),
                ('hour',np.float16),
                ('minute',np.float16),
                 ('temp',np.float16)])
np_data=np.loadtxt('weather1week.csv',dtype=schems,delimiter=';')
np_data

In [ ]:
np_data[0]

In [ ]:
np_data['temp']

In [ ]:
np_data['temp']=np_data['temp']*(9/5)+32
np_data

In [ ]:
schems=np.dtype([('year',np.float16),
                 ('month',np.float16),
                 ('day',np.float16),
                 ('hour',np.float16),
                 ('minute',np.float16),
                 ('temp',np.float16),
                 ('temp1',np.float16)])
np_data=np.loadtxt('weatherComp.csv',dtype=schems,delimiter=';')
np_data
                 

In [ ]:
a=np_data['temp'].max()
print(a)
b=np_data['temp1'].max()
print(b)
if(a>b):
    print(a,"2017 is hot")
else:
    print(b,"2018 is hot")

In [ ]:
#create a array 100 elements 
a=np.linspace(1,100,num=100,dtype=int)
a
b=a.reshpae((1,100)
print(b)


# pandas

In [ ]:
import numpy as np
import pandas as pd

In [77]:
schema=np.dtype([('sepal_length',np.float16),('sepal_width',np.float16),('petal_length',np.float16),('petal_width',np.float16),
                ('species','<U16')])


In [78]:
np_data=np.loadtxt('iris.csv',dtype=schema,delimiter=',')
np_data

array([(5.1, 3.5, 1.4, 0.2, 'setosa'), (4.9, 3. , 1.4, 0.2, 'setosa'),
       (4.7, 3.2, 1.3, 0.2, 'setosa'), (4.6, 3.1, 1.5, 0.2, 'setosa'),
       (5. , 3.6, 1.4, 0.2, 'setosa'), (5.4, 3.9, 1.7, 0.4, 'setosa'),
       (4.6, 3.4, 1.4, 0.3, 'setosa'), (5. , 3.4, 1.5, 0.2, 'setosa'),
       (4.4, 2.9, 1.4, 0.2, 'setosa'), (4.9, 3.1, 1.5, 0.1, 'setosa'),
       (5.4, 3.7, 1.5, 0.2, 'setosa'), (4.8, 3.4, 1.6, 0.2, 'setosa'),
       (4.8, 3. , 1.4, 0.1, 'setosa'), (4.3, 3. , 1.1, 0.1, 'setosa'),
       (5.8, 4. , 1.2, 0.2, 'setosa'), (5.7, 4.4, 1.5, 0.4, 'setosa'),
       (5.4, 3.9, 1.3, 0.4, 'setosa'), (5.1, 3.5, 1.4, 0.3, 'setosa'),
       (5.7, 3.8, 1.7, 0.3, 'setosa'), (5.1, 3.8, 1.5, 0.3, 'setosa'),
       (5.4, 3.4, 1.7, 0.2, 'setosa'), (5.1, 3.7, 1.5, 0.4, 'setosa'),
       (4.6, 3.6, 1. , 0.2, 'setosa'), (5.1, 3.3, 1.7, 0.5, 'setosa'),
       (4.8, 3.4, 1.9, 0.2, 'setosa'), (5. , 3. , 1.6, 0.2, 'setosa'),
       (5. , 3.4, 1.6, 0.4, 'setosa'), (5.2, 3.5, 1.5, 0.2, 'setosa'),
      

In [ ]:
np_data[0]

In [ ]:
np_data['species']

In [79]:
pd_data=pd.read_csv('irish.csv')
pd_data.head()

SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [ ]:
pd_data=pd.read_csv('iris.csv',names=['sepal_length','sepal_width','petal_length','petal_width','species'])
pd_data.head()

In [ ]:
pd_data.sepal_length

In [ ]:
pd_data=pd.read_csv('iris.csv',usecols=[0,1,4],names=['sepal_length','sepal_width','species'])
pd_data.head()
#you have header in your file d'not use names

In [ ]:
pd_data.shape

In [ ]:
pd_data.dtypes

In [ ]:
pd_data.get_dtype_counts()

In [ ]:
pd_data.isnull().values.any()

In [ ]:
pd_csv=pd.read_csv('tweets_withHeader.csv')
pd_csv.head()

In [ ]:
pd_csv=pd.read_csv('tweets_noHeader.csv',names=['id','polarity','text'])
pd_csv.head()

In [ ]:
pd_w=pd.read_csv('weather1week.csv',names=['year','month','day','hours','mini','temp'],delimiter=';')
pd_w.head()

# pandas

In [1]:
import pandas as pd
print(pd.__version__)

0.23.4


In [ ]:
s=pd.Series([0,1,4,9,16,25],name='squares')
s

In [ ]:
s.values

In [ ]:
s.index

In [ ]:
s[2]

In [ ]:
s[1:4]

# creating dataframes

In [ ]:
mat=np.arange(0,9).reshape(3,3)
mat

In [ ]:
pd.DataFrame(mat)

In [ ]:
arr=[(1,'a'),(2,'b'),(3,'b')]
pd.DataFrame(arr,columns=['Letters','Numbers'])

In [ ]:
dictDf={'Numbers':[1,2,3],'Letters':['a','b','c']}
pd.DataFrame(dictDf)

In [ ]:
dictDf={'Numbers':[1,2,3,4],'Letters':['a','b','c']}
pd.DataFrame(dictDf)

In [12]:
ser1=pd.Series([24,30,10,23,32,43],name='age')
ser2=pd.Series(['ram','raj','gowri','shankar'],name='name')
pd.DataFrame({"age":ser1,"name":ser2})

age     name
0   24      ram
1   30      raj
2   10    gowri
3   23  shankar
4   32      NaN
5   43      NaN

In [13]:
pd.DataFrame([ser1,ser2])

0    1      2        3     4     5
age    24   30     10       23  32.0  43.0
name  ram  raj  gowri  shankar   NaN   NaN

In [14]:
pd.DataFrame([ser1,ser2]).T

age     name
0  24      ram
1  30      raj
2  10    gowri
3  23  shankar
4  32      NaN
5  43      NaN

In [15]:
a=[2,4,6,8,10]
pd.DataFrame(a)

0
0   2
1   4
2   6
3   8
4  10

In [16]:
s1=pd.Series(['sivaji','kgf','kabali','bagubali','ranimurugan'],name='Moviesnames')
s2=pd.Series(['rajini','yash','rajini','birabas','sivakarthikavayan'],name='lead male')
s3=pd.Series([],name='lead female')
s4=pd.Series(['1','1','1','1','1'],name='remark')
pd.DataFrame([s1,s2,s3,s4]).T

Moviesnames          lead male lead female remark
0       sivaji             rajini         NaN      1
1          kgf               yash         NaN      1
2       kabali             rajini         NaN      1
3     bagubali            birabas         NaN      1
4  ranimurugan  sivakarthikavayan         NaN      1

In [17]:
age=pd.DataFrame([ser1,ser2]).T
age

age     name
0  24      ram
1  30      raj
2  10    gowri
3  23  shankar
4  32      NaN
5  43      NaN

In [18]:
age['app_range']=[1 if a<=15 else 2 if 15<a<50 else 3 for a in age['age']]
age

age     name  app_range
0  24      ram          2
1  30      raj          2
2  10    gowri          1
3  23  shankar          2
4  32      NaN          2
5  43      NaN          2

In [19]:
age.append(pd.DataFrame({'age':pd.Series(31),'name':pd.Series('GOWRI'),'age_range':pd.Series(2)}))


C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


age  age_range  app_range     name
0  24        NaN        2.0      ram
1  30        NaN        2.0      raj
2  10        NaN        1.0    gowri
3  23        NaN        2.0  shankar
4  32        NaN        2.0      NaN
5  43        NaN        2.0      NaN
0  31        2.0        NaN    GOWRI

In [1]:
pd.DataFrame(a)

NameError: name 'pd' is not defined

In [21]:
a['3m']=[1 if b/2==0 else 0 for b in a['a']]
a

TypeError: list indices must be integers or slices, not str

In [23]:
age.to_csv('age.csv')

In [24]:
#computer language popularity in 2017
pop2017=pd.Series([100,99.7,99.5,97.1,87.7,87.7,85.6,81.2,75.1,73.1],index=['python','c','java','c++','c#','R','javascript','go','rdbms','matlab'])
pop2017

python        100.0
c              99.7
java           99.5
c++            97.1
c#             87.7
R              87.7
javascript     85.6
go             81.2
rdbms          75.1
matlab         73.1
dtype: float64

In [25]:
pop2017[1]

99.7

In [26]:
pop2017['c']

99.7

In [30]:
pop2017.index

Index(['python', 'c', 'java', 'c++', 'c#', 'R', 'javascript', 'go', 'rdbms',
       'matlab'],
      dtype='object')

In [32]:
pop2017['c':'go']

c             99.7
java          99.5
c++           97.1
c#            87.7
R             87.7
javascript    85.6
go            81.2
dtype: float64

In [33]:
pop2017.iloc[0:2]

python    100.0
c          99.7
dtype: float64

In [35]:
pop2017[:'R']

python    100.0
c          99.7
java       99.5
c++        97.1
c#         87.7
R          87.7
dtype: float64

In [36]:
pop2017[pop2017>99.5]

python    100.0
c          99.7
dtype: float64

In [40]:
pop2017=pd.Series({'python':100,'c':99.7,'java':99.5,'c++':97.1,'c#':87.7,'R':87.7,'javascript':85.6,'go':81.2,'php':81.5})
pop2017

python        100.0
c              99.7
java           99.5
c++            97.1
c#             87.7
R              87.7
javascript     85.6
go             81.2
php            81.5
dtype: float64

In [63]:
pd_csv=pd.read_csv('weatherComp.csv',names=['year','month','date','hour','minite','temp_1','temp_2'],delimiter=';')
pd_csv[pd_csv['date']==10]
df1=pd_csv[pd_csv['date']==10]
df2=df1[df1['hour']==10]
print(df2)
df3=df1[df1['hour']==22]
print(df3)

    year  month  date  hour  minite  temp_1  temp_2
34  2018      9    10    10       0   26.92   26.88
    year  month  date  hour  minite  temp_1  temp_2
46  2018      9    10    22       0   22.23   22.71


In [67]:
pop2014=pd.Series({'python':31.21,'java':19.5,'c++':9.7,'c#':7.3})
print(pop2014)
pop2015=pd.Series({'python':31.21,'java':19.5,'c++':9.7,'c#':7.3})
print(pop2015)

python    31.21
java      19.50
c++        9.70
c#         7.30
dtype: float64
python    31.21
java      19.50
c++        9.70
c#         7.30
dtype: float64


In [68]:
twoyear=pd.DataFrame({'2014':pop2014,'2015':pop2015})
twoyear

2014   2015
python  31.21  31.21
java    19.50  19.50
c++      9.70   9.70
c#       7.30   7.30

In [71]:
twoyears1=pd.concat([pop2014,pop2015],axis=1)
twoyears1

0      1
python  31.21  31.21
java    19.50  19.50
c++      9.70   9.70
c#       7.30   7.30

In [72]:
pop2014.name='2014'
pop2015.name='2015'
twoyears1=pd.concat([pop2014,pop2015],axis=1)
twoyears1

2014   2015
python  31.21  31.21
java    19.50  19.50
c++      9.70   9.70
c#       7.30   7.30

In [73]:
twoyear.values

array([[31.21, 31.21],
       [19.5 , 19.5 ],
       [ 9.7 ,  9.7 ],
       [ 7.3 ,  7.3 ]])

In [75]:
twoyear.columns

Index(['2014', '2015'], dtype='object')

In [76]:
twoyear['2014']

python    31.21
java      19.50
c++        9.70
c#         7.30
Name: 2014, dtype: float64

In [77]:
twoyear.loc['python':'c']

2014   2015
python  31.21  31.21
java    19.50  19.50
c++      9.70   9.70
c#       7.30   7.30

In [79]:
twoyear.iloc[1:3]

2014  2015
java  19.5  19.5
c++    9.7   9.7

In [80]:
twoyear.iloc[1:5+1,1:2]

2015
java  19.5
c++    9.7
c#     7.3

In [86]:
twoyear.loc['python':'c#','2014']

python    31.21
java      19.50
c++        9.70
c#         7.30
Name: 2014, dtype: float64

# location identify

In [91]:
twoyear.loc[['c++','c#','python']]

2014   2015
c++      9.70   9.70
c#       7.30   7.30
python  31.21  31.21

In [90]:
twoyearcopy=twoyear.iloc[:,0:2].loc[['python','c++','c#']].copy()
twoyearcopy

2014   2015
python  31.21  31.21
c++      9.70   9.70
c#       7.30   7.30

In [92]:
twoyearcopy['2015']=pd.Series({'c++':1,'c#':1,'python':1})
twoyearcopy

2014  2015
python  31.21     1
c++      9.70     1
c#       7.30     1

In [98]:
twoyearcopy.iloc[2,1]=5
twoyearcopy

2014  2015
python  31.21    -1
c++      9.70    -1
c#       7.30     5

In [94]:
twoyearcopy.iloc[:,1]=-1
twoyearcopy

2014  2015
python  31.21    -1
c++      9.70    -1
c#       7.30    -1

In [97]:
twoyear.iloc[1,:]=-1
twoyear

2014   2015
python  31.21  31.21
java    -1.00  -1.00
c++      9.70   9.70
c#       7.30   7.30

# creating new columns

In [103]:
twoyear['average']=(twoyear['2014']+twoyear['2015'])/2
twoyear

2014   2015  average
python  31.21  31.21    31.21
java    -1.00  -1.00    -1.00
c++      9.70   9.70     9.70
c#       7.30   7.30     7.30

In [104]:
twoyear.2014

SyntaxError: invalid syntax (<ipython-input-104-f1d6433ceb35>, line 1)

In [105]:
twoyear['2014']

python    31.21
java      -1.00
c++        9.70
c#         7.30
Name: 2014, dtype: float64

In [2]:
import numpy as np
import pandas as pd
pd_ch=pd.Series(np.random.randint(100,150,size=5),name='height(cm)')
pd_wi=pd.Series(np.random.randint(150,200,size=5),name='wight(kg)')
data=pd.DataFrame([pd_ch,pd_wi]).T
data['height(meter)']=(data['height(cm)'])/100
data['bmi']=(data['wight(kg)']/(data['height(meter)']**2))
data

height(cm)  wight(kg)  height(meter)         bmi
0         125        157           1.25  100.480000
1         137        153           1.37   81.517396
2         123        184           1.23  121.620728
3         133        175           1.33   98.931539
4         135        187           1.35  102.606310

# 20.5.2019 vectorization

In [4]:
@np.vectorize
def turnc(x):
    return x if x>0 else 0

In [5]:
s=pd.Series([5,-5,2,-2,3,-3])
s

0    5
1   -5
2    2
3   -2
4    3
5   -3
dtype: int64

In [6]:
turnc(s)

array([5, 0, 2, 0, 3, 0], dtype=int64)

In [11]:
d=pd.DataFrame([[1,-1,2,-2],[3,-1,4,-4]])
d

0  1  2  3
0  1 -1  2 -2
1  3 -1  4 -4

In [12]:
turnc(d)

array([[1, 0, 2, 0],
       [3, 0, 4, 0]], dtype=int64)

In [32]:
#create a dataframe of 5 rows and 3 colums
#write a function to find the square root of the value in the df 
#write a function to return only the whole number for all decimal number
a=(np.random.randint(1,10,(5,3)))
b=pd.DataFrame(a)
b

0  1  2
0  1  1  7
1  6  4  5
2  6  2  6
3  5  2  6
4  3  2  1

In [39]:
@np.vectorize
def sqrt(b):
    return np.sqrt(b)


In [40]:
sqrt(b)

array([[1.        , 1.        , 2.64575131],
       [2.44948974, 2.        , 2.23606798],
       [2.44948974, 1.41421356, 2.44948974],
       [2.23606798, 1.41421356, 2.44948974],
       [1.73205081, 1.41421356, 1.        ]])

In [54]:
df=pd.DataFrame(np.arange(15).reshape(5,3),columns=['c1','c2','c3'])
df

c1  c2  c3
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [55]:
df2=pd.DataFrame(np.arange(10,20).reshape(5,2),columns=['c1','c3'])
df2

c1  c3
0  10  11
1  12  13
2  14  15
3  16  17
4  18  19

In [56]:
df2-df

c1  c2  c3
0  10 NaN   9
1   9 NaN   8
2   8 NaN   7
3   7 NaN   6
4   6 NaN   5

In [57]:
df.std()

c1    4.743416
c2    4.743416
c3    4.743416
dtype: float64

In [58]:
np.sqrt(df)

c1        c2        c3
0  0.000000  1.000000  1.414214
1  1.732051  2.000000  2.236068
2  2.449490  2.645751  2.828427
3  3.000000  3.162278  3.316625
4  3.464102  3.605551  3.741657

In [59]:
df.mean()

c1    6.0
c2    7.0
c3    8.0
dtype: float64

In [60]:
type(df.mean())

pandas.core.series.Series

In [61]:
turnc(np.sqrt(df))

array([[0, 1, 1],
       [1, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3]])

# select columns with the specific data types

In [64]:
df2=pd.DataFrame({'AAA':[1,2,3,4],'BBB':[5,6,7,8],'STR':['a','b','c','d']})
df2

AAA  BBB STR
0    1    5   a
1    2    6   b
2    3    7   c
3    4    8   d

In [65]:
np.sqrt(df2)

AttributeError: 'int' object has no attribute 'sqrt'

In [66]:
np.sqrt(df2.loc[:,['AAA','BBB']])

AAA       BBB
0  1.000000  2.236068
1  1.414214  2.449490
2  1.732051  2.645751
3  2.000000  2.828427

In [67]:
df2.select_dtypes([np.number])

AAA  BBB
0    1    5
1    2    6
2    3    7
3    4    8

In [68]:
np.sqrt(df2.select_dtypes([np.number]))

AAA       BBB
0  1.000000  2.236068
1  1.414214  2.449490
2  1.732051  2.645751
3  2.000000  2.828427

In [69]:
df

c1  c2  c3
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [73]:
df['c3']=df['c3'].apply(lambda a:1 if a%2==0 else 0)                       
df

c1  c2  c3
0   0   1   1
1   3   4   0
2   6   7   1
3   9  10   0
4  12  13   1

In [75]:
df3=df.copy()
df3=df3.applymap(lambda a:1 if a%2==0 else 0)
df3

c1  c2  c3
0   1   0   0
1   0   1   1
2   1   0   0
3   0   1   1
4   1   0   0

In [80]:
df3[df3['c1']>0]

c1  c2  c3
0   1   0   0
2   1   0   0
4   1   0   0

In [81]:
pd_data

SepalLength  SepalWidth  PetalLength  PetalWidth    Species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
5            5.4         3.9          1.7         0.4     setosa
6            4.6         3.4          1.4         0.3     setosa
7            5.0         3.4          1.5         0.2     setosa
8            4.4         2.9          1.4         0.2     setosa
9            4.9         3.1          1.5         0.1     setosa
10           5.4         3.7          1.5         0.2     setosa
11           4.8         3.4          1.6         0.2     setosa
12           4.8         3.0          1.4         0.1     setosa
13           4.3         3.0          1.1         0.1     setosa
14           5.8         4.0          1.2         0.2     setosa
15           5.7         4.4          1.5         0.4     setosa
16           5.4         3.9          1.3         0.4     setosa
17           5.1         3.5          1.4         0.3     setosa
18           5.7         3.8          1.7         0.3     setosa
19           5.1         3.8          1.5         0.3     setosa
20           5.4         3.4          1.7         0.2     setosa
21           5.1         3.7          1.5         0.4     setosa
22           4.6         3.6          1.0         0.2     setosa
23           5.1         3.3          1.7         0.5     setosa
24           4.8         3.4          1.9         0.2     setosa
25           5.0         3.0          1.6         0.2     setosa
26           5.0         3.4          1.6         0.4     setosa
27           5.2         3.5          1.5         0.2     setosa
28           5.2         3.4          1.4         0.2     setosa
29           4.7         3.2          1.6         0.2     setosa
..           ...         ...          ...         ...        ...
120          6.9         3.2          5.7         2.3  virginica
121          5.6         2.8          4.9         2.0  virginica
122          7.7         2.8          6.7         2.0  virginica
123          6.3         2.7          4.9         1.8  virginica
124          6.7         3.3          5.7         2.1  virginica
125          7.2         3.2          6.0         1.8  virginica
126          6.2         2.8          4.8         1.8  virginica
127          6.1         3.0          4.9         1.8  virginica
128          6.4         2.8          5.6         2.1  virginica
129          7.2         3.0          5.8         1.6  virginica
130          7.4         2.8          6.1         1.9  virginica
131          7.9         3.8          6.4         2.0  virginica
132          6.4         2.8          5.6         2.2  virginica
133          6.3         2.8          5.1         1.5  virginica
134          6.1         2.6          5.6         1.4  virginica
135          7.7         3.0          6.1         2.3  virginica
136          6.3         3.4          5.6         2.4  virginica
137          6.4         3.1          5.5         1.8  virginica
138          6.0         3.0          4.8         1.8  virginica
139          6.9         3.1          5.4         2.1  virginica
140          6.7         3.1          5.6         2.4  virginica
141          6.9         3.1          5.1         2.3  virginica
142          5.8         2.7          5.1         1.9  virginica
143          6.8         3.2          5.9         2.3  virginica
144          6.7         3.3          5.7         2.5  virginica
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.

In [83]:
pd_data.tail()

SepalLength  SepalWidth  PetalLength  PetalWidth    Species
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

In [84]:
pd_data[pd_data['Species']=='setosa']

SepalLength  SepalWidth  PetalLength  PetalWidth Species
0           5.1         3.5          1.4         0.2  setosa
1           4.9         3.0          1.4         0.2  setosa
2           4.7         3.2          1.3         0.2  setosa
3           4.6         3.1          1.5         0.2  setosa
4           5.0         3.6          1.4         0.2  setosa
5           5.4         3.9          1.7         0.4  setosa
6           4.6         3.4          1.4         0.3  setosa
7           5.0         3.4          1.5         0.2  setosa
8           4.4         2.9          1.4         0.2  setosa
9           4.9         3.1          1.5         0.1  setosa
10          5.4         3.7          1.5         0.2  setosa
11          4.8         3.4          1.6         0.2  setosa
12          4.8         3.0          1.4         0.1  setosa
13          4.3         3.0          1.1         0.1  setosa
14          5.8         4.0          1.2         0.2  setosa
15          5.7         4.4          1.5         0.4  setosa
16          5.4         3.9          1.3         0.4  setosa
17          5.1         3.5          1.4         0.3  setosa
18          5.7         3.8          1.7         0.3  setosa
19          5.1         3.8          1.5         0.3  setosa
20          5.4         3.4          1.7         0.2  setosa
21          5.1         3.7          1.5         0.4  setosa
22          4.6         3.6          1.0         0.2  setosa
23          5.1         3.3          1.7         0.5  setosa
24          4.8         3.4          1.9         0.2  setosa
25          5.0         3.0          1.6         0.2  setosa
26          5.0         3.4          1.6         0.4  setosa
27          5.2         3.5          1.5         0.2  setosa
28          5.2         3.4          1.4         0.2  setosa
29          4.7         3.2          1.6         0.2  setosa
30          4.8         3.1          1.6         0.2  setosa
31          5.4         3.4          1.5         0.4  setosa
32          5.2         4.1          1.5         0.1  setosa
33          5.5         4.2          1.4         0.2  setosa
34          4.9         3.1          1.5         0.1  setosa
35          5.0         3.2          1.2         0.2  setosa
36          5.5         3.5          1.3         0.2  setosa
37          4.9         3.1          1.5         0.1  setosa
38          4.4         3.0          1.3         0.2  setosa
39          5.1         3.4          1.5         0.2  setosa
40          5.0         3.5          1.3         0.3  setosa
41          4.5         2.3          1.3         0.3  setosa
42          4.4         3.2          1.3         0.2  setosa
43          5.0         3.5          1.6         0.6  setosa
44          5.1         3.8          1.9         0.4  setosa
45          4.8         3.0          1.4         0.3  setosa
46          5.1         3.8          1.6         0.2  setosa
47          4.6         3.2          1.4         0.2  setosa
48          5.3         3.7          1.5         0.2  setosa
49          5.0         3.3          1.4         0.2  setosa

In [91]:
pd_data[(pd_data['Species']=='setosa') & (pd_data['SepalLength']>5.5)]

SepalLength  SepalWidth  PetalLength  PetalWidth Species
14          5.8         4.0          1.2         0.2  setosa
15          5.7         4.4          1.5         0.4  setosa
18          5.7         3.8          1.7         0.3  setosa

# let's work with the presidents

In [95]:
presidents=pd.DataFrame([{'name':'Donald Trump','Iyear':2017,'byear':1908},
                         {'name':'bauack obama','Iyear':2009,'byear':1903},
                         {'name':'george w.bush','Iyear':2001,'byear':1900},
                         {'name':'bill clinton','Iyear':1993,'byear':1946}])

In [96]:
presidents

Iyear  byear           name
0   2017   1908   Donald Trump
1   2009   1903   bauack obama
2   2001   1900  george w.bush
3   1993   1946   bill clinton

In [97]:
presidents_indexes=presidents.set_index('name')
presidents_indexes

Iyear  byear
name                       
Donald Trump    2017   1908
bauack obama    2009   1903
george w.bush   2001   1900
bill clinton    1993   1946

In [99]:
presidents_indexes.loc['Donald Trump']

Iyear    2017
byear    1908
Name: Donald Trump, dtype: int64

In [100]:
presidents_indexes.loc['bill clinton']['byear']

1946

In [101]:
presidents_indexes.loc['bill clinton','byear']

1946

In [102]:
presidents_indexes['byear','bill clinton']

KeyError: ('byear', 'bill clinton')

In [103]:
presidents_indexes['byear']['bill clinton']

1946

In [2]:
import pandas as pd
presidents_fathers=pd.DataFrame([{'son':'Donald Trump','father':'Fred Trump'},
                                {'son':'Barack Obama','father':'Barack Obama Sr.'},
                                {'son':'George w.Bush','father':'George w h Bush'}])
presidents_fathers

father            son
0        Fred Trump   Donald Trump
1  Barack Obama Sr.   Barack Obama
2   George w h Bush  George w.Bush

In [106]:
pd.merge(presidents,presidents_fathers,left_on='name',right_on='son')

Iyear  byear          name      father           son
0   2017   1908  Donald Trump  Fred Trump  Donald Trump

In [107]:
presidents

Iyear  byear           name
0   2017   1908   Donald Trump
1   2009   1903   bauack obama
2   2001   1900  george w.bush
3   1993   1946   bill clinton

In [108]:
pd.merge(presidents,presidents_fathers,left_on='name',right_on='son').drop('son',axis=1)

Iyear  byear          name      father
0   2017   1908  Donald Trump  Fred Trump

In [110]:
pd.merge(presidents,presidents_fathers,left_on='name',right_on='son',how='left').drop('son',axis=1)

Iyear  byear           name      father
0   2017   1908   Donald Trump  Fred Trump
1   2009   1903   bauack obama         NaN
2   2001   1900  george w.bush         NaN
3   1993   1946   bill clinton         NaN

# handling nans

In [3]:
import numpy as np
import pandas as pd
import random
vals=np.random.randn(21)
vals[random.sample([i for i in range(21)],5)]=np.nan
df=pd.DataFrame(vals.reshape(7,3),columns=['c1','c2','c3'])
df

c1        c2        c3
0 -0.103319 -0.573384       NaN
1 -0.474923       NaN  0.468692
2  0.206333  0.955695 -0.039560
3 -0.297169  0.251454  1.024811
4  0.169312       NaN -0.161046
5 -0.604401       NaN       NaN
6  2.216633 -1.098846 -0.464442

In [117]:
np.isnan(df)

c1     c2     c3
0   True  False  False
1  False  False  False
2  False   True  False
3  False  False   True
4   True  False  False
5   True  False  False
6  False  False  False

In [118]:
len(df)

7

In [120]:
df.count()

c1    4
c2    6
c3    6
dtype: int64

In [121]:
df2=df.dropna()
df2

c1        c2        c3
1 -1.373603 -1.866854 -0.266135
6  1.798971 -0.662825  0.996574

In [122]:
df2.count()

c1    2
c2    2
c3    2
dtype: int64

In [123]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [124]:
df

c1        c2        c3
0       NaN  0.413041  1.103811
1 -1.373603 -1.866854 -0.266135
2  0.243972       NaN  1.553149
3 -1.289908 -0.722231       NaN
4       NaN -0.711160  0.886703
5       NaN -1.188146  1.364177
6  1.798971 -0.662825  0.996574

In [125]:
df.fillna(0)

c1        c2        c3
0  0.000000  0.413041  1.103811
1 -1.373603 -1.866854 -0.266135
2  0.243972  0.000000  1.553149
3 -1.289908 -0.722231  0.000000
4  0.000000 -0.711160  0.886703
5  0.000000 -1.188146  1.364177
6  1.798971 -0.662825  0.996574

In [127]:
df.fillna(df.mean())

c1        c2        c3
0 -0.155142  0.413041  1.103811
1 -1.373603 -1.866854 -0.266135
2  0.243972 -0.789696  1.553149
3 -1.289908 -0.722231  0.939713
4 -0.155142 -0.711160  0.886703
5 -0.155142 -1.188146  1.364177
6  1.798971 -0.662825  0.996574

# indices

In [133]:
import seaborn

In [134]:
flights=seaborn.load_dataset('flights')

In [135]:
flights.head()

year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [138]:
flights_indexed=flights.set_index('year','month')
flights_indexed.head()

month  passengers
year                      
1949   January         112
1949  February         118
1949     March         132
1949     April         129
1949       May         121

In [140]:
flights_indexed

month  passengers
year                       
1949    January         112
1949   February         118
1949      March         132
1949      April         129
1949        May         121
1949       June         135
1949       July         148
1949     August         148
1949  September         136
1949    October         119
1949   November         104
1949   December         118
1950    January         115
1950   February         126
1950      March         141
1950      April         135
1950        May         125
1950       June         149
1950       July         170
1950     August         170
1950  September         158
1950    October         133
1950   November         114
1950   December         140
1951    January         145
1951   February         150
1951      March         178
1951      April         163
1951        May         172
1951       June         178
...         ...         ...
1958       July         491
1958     August         505
1958  September         404
1958    October         359
1958   November         310
1958   December         337
1959    January         360
1959   February         342
1959      March         406
1959      April         396
1959        May         420
1959       June         472
1959       July         548
1959     August         559
1959  September         463
1959    October         407
1959   November         362
1959   December         405
1960    January         417
1960   February         391
1960      March         419
1960      April         461
1960        May         472
1960       June         535
1960       July         622
1960     August         606
1960  September         508
1960    October         461
1960   November         390
1960   December         432

[144 rows x 2 columns]

In [141]:
flights_indexed.loc[1949]

month  passengers
year                       
1949    January         112
1949   February         118
1949      March         132
1949      April         129
1949        May         121
1949       June         135
1949       July         148
1949     August         148
1949  September         136
1949    October         119
1949   November         104
1949   December         118

In [143]:
flights[flights.year==1950]

year      month  passengers
12  1950    January         115
13  1950   February         126
14  1950      March         141
15  1950      April         135
16  1950        May         125
17  1950       June         149
18  1950       July         170
19  1950     August         170
20  1950  September         158
21  1950    October         133
22  1950   November         114
23  1950   December         140

In [144]:
flights_indexed.loc[1949:1950]

month  passengers
year                       
1949    January         112
1949   February         118
1949      March         132
1949      April         129
1949        May         121
1949       June         135
1949       July         148
1949     August         148
1949  September         136
1949    October         119
1949   November         104
1949   December         118
1950    January         115
1950   February         126
1950      March         141
1950      April         135
1950        May         125
1950       June         149
1950       July         170
1950     August         170
1950  September         158
1950    October         133
1950   November         114
1950   December         140

In [147]:
flights_indexed.loc[1949,'May']

KeyError: 'the label [May] is not in the [columns]'

In [148]:
flights_indexed.loc['May:June']

KeyError: 'the label [May:June] is not in the [index]'

In [149]:
flights_unstacked=flights_indexed.unstack()
flights_unstacked

            year
month       1949      January
            1949     February
            1949        March
            1949        April
            1949          May
            1949         June
            1949         July
            1949       August
            1949    September
            1949      October
            1949     November
            1949     December
            1950      January
            1950     February
            1950        March
            1950        April
            1950          May
            1950         June
            1950         July
            1950       August
            1950    September
            1950      October
            1950     November
            1950     December
            1951      January
            1951     February
            1951        March
            1951        April
            1951          May
            1951         June
                      ...    
passengers  1958          491
            1958       

In [5]:
flights_unstacked.sum(axis=1)

NameError: name 'flights_unstacked' is not defined