In [1]:
a='hello'

In [2]:
print(a)

hello


In [ ]:
string1='hello'
string2="my friend"

string3="""welcome to all
in new day"""

print(string1)
print(string2)
print(string3)

In [ ]:
name='gowrishankar'

address="""37, 4th street,
arasu colony,e.pudur,trichy-12."""

print(name)
print(address)


In [ ]:
name='gowri'
name1='shankr'
id(name), id(name1)


In [ ]:
id(a)

In [ ]:

a=10
b=20
print(id(a),id(b))

In [ ]:
#float doesnot show same value in id function
a=13.4
b=13.4
print(id(a),id(b))

In [ ]:
#precision problems in floats
c=.1+.1+.1-.3
print(c)

In [ ]:
#precision vs accuracy tradeoff

from decimal import *
a=Decimal('0.1')
b=Decimal('0.3')

c=a+a+a-b
print (f"the result is {c}")

In [ ]:
pi=3.14
type(pi)

In [ ]:
#if , else, elif 
a=16

if(a%3==0 and a%5==0):
    print("frizz buzz")
elif(a%3==0):
    print("frizz")
elif(a%5==0):
    print("buzz")
else:
    print("none")

In [ ]:
#ternary operator
mark=100

result="pass" if(mark>50) else "fail"

print("mark= {}".format(mark))
print("result= {}".format(result))

In [ ]:
#swap
a=10
b=20
tmp=0

tmp=a
a=b
b=tmp

print(a,b)

In [ ]:
#find area of a triangle
b=10
h=10
c=(0.5 * b* h)
print(f"area of triangle{c}")

In [ ]:
a=10
b=0.621
miles=(a*b)
print(miles)

In [ ]:
#odd or even

a=5

value="odd" if(a%2==0) else "even"
print(value)

In [ ]:
#leap year 
a=1996
year="leap" if(a%4==0) else "not leap"
print(year)

In [ ]:
#positive or negative or zero
a=int(input("enter the good number"))
if(a>0):
    print("positive")
elif(a==0):
    print("zero")
else:
    print("negative")

    


In [ ]:
#loop

value=int(input("enter the good number"))

while(value<9):
    print(value)
    value=value+1


In [ ]:
password="gowri"
pwd=""

while pwd!=password:
    pwd=input("enter your password:")

print=("password correct!! \nwelcome")
    

In [1]:
#for loop

days=['sun','mon','tue','wed','thu','fri','sat']

for a in days:
    print("a")

a
a
a
a
a
a
a


In [ ]:
list(range(20))

In [3]:
for x in range(0,10):
    print(x)
    

0
1
2
3
4
5
6
7
8
9


#multiples of 2 using range
for x in range(0,10,2):
    print(x)

In [4]:
#multiples of 5 using range staring from 10 and ending in 100
for x in range(10,100,5):
    print(x)

10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95


In [1]:
type(n)

NameError: name 'n' is not defined

In [9]:
#first n multiples of 5 using a for loop
n=input("enter the number:")
n=int(n)
for x in range(0,n+1):
    print(x*5)

enter the number:4
0
5
10
15
20


In [10]:
#enumerate
day=['sun','mon','tue','wed','thu','fri','sat']
for index,data in enumerate(day):
    print(f"{index} :::> {data}")

0 :::> sun
1 :::> mon
2 :::> tue
3 :::> wed
4 :::> thu
5 :::> fri
6 :::> sat


In [ ]:
n="gowri"
for index,data in enumerate(n):
    print(f"{index}---> {data}")

In [ ]:
password="gowri"
pwd=''
count=0

while pwd!=password:
    if count==5:
        break
        count +=1
        pwd=input(f"attempt {count}:enter your password:")

if (pwd==password):
    print("authorized... \nwelcome you")
else:
    print("wrong password")
                
    

In [2]:
#break and continue
animals=['dog','cat','parrot','lion','tiger']
for animals in animals:
    if(animals=='fish'):
        continue
    
    if(animals=='parrot'):
        print("error !! exiting!!  we have a bird")
        break
    print(animals)
else:
    print("printed all animals")

dog
cat
error !! exiting!!  we have a bird


In [3]:
days=['sun','mon','tue','wed','thu','fri','sat']

for days in days:
    if(days=='sun'):
        print("SUNDAY")
        continue
    if(days=='mon'):
        print("i hate monday")
        continue
    if(days=='thu'):
        continue
        
    print(days)
                    

SUNDAY
i hate monday
tue
wed
fri
sat


In [ ]:
#read two number print their quotient an remainder
a=int(input("enter first number:"))
b=int(input("enter secound number:"))
q=a/b
r=a%b
print(f"quotient:{q}")
print(f"remainder:{r}")

In [ ]:
#factorial n number
n=int(input("enrer the number:"))
fact=1
i=1
while(i<n+1):
    fact=fact*i
    i=i+1
print(fact)

In [ ]:
a=int(input("enter the number:"))

while(a>0):
    x=a%10
    b=a/10
if(b==a):
    print("a is same number")
else:
    print("sum error occure")
print(x)


In [ ]:
x=int(input("enter the number:"))
for x in range(9,x,9):
    print(x)

In [ ]:
#swap variables
a=int(input("enter the number"))
b=int(input("enter the number"))

a=a^b
#b=a^b

print(a)
print(b)

In [ ]:
#leap year
x=int(input("enter the number:"))
if(x%4==0 and x%100==0):
    print("leap year")
elif(x%400==0):
    print("not leap")

In [ ]:
#sum of all natural number
a=9
for b in range(1,a+1,1):
        print(b)
    

In [ ]:
#leapyear in function

year=int(input("enter the year"));

def isleapyear(int year)
{
    istypicalleapyear(year) && not(isatypicalcommonyear(year);                            
}
def istypicalleapyear(int year)
{
    year % 4 == 0;
}
def isatypicalcommonyear(int year)
{
    year % 100 == 0 && not(year % 400 == 0);
}

In [ ]:
#try catch
try:
    a=0/0
    f=open("hello.txt","r")
    print(r.read())
except:
    print("error in opening file")

In [ ]:
#try catch II
try:
    #a=0/0
    f=open("hello.txt","r")
    print(r.read())
except IOError:
    print("error in opeing file")
except:
    print("error")

In [ ]:
#USER INPUT
a=input("enter the value of a")
a

In [ ]:
#file handling 

f=open("fil.txt","w")
f.write("hi welcome, \n i am your friend")
f.close()

In [ ]:
f=open("fil.txt","r")
a=f.read()
f.close()
print(a)

In [ ]:
with open("fil.txt","r") as f:
    for line in f:
        print(line)

In [ ]:
f=open("fil.txt","r")
a=f.readlines()
f.close()
print(a)

In [ ]:
with open("fil.txt","r")as f:
    for i,line in enumerate(f):
        print(i,line)

In [ ]:
f=open("fil.txt","a")
a=f.write("welcome too all")
f.close()
print(a)

In [ ]:
import csv
filename="tweets_withheader.csv"
with open(filename,"r")as f:
    data_reader=csv.reader(f,delimiter=',')
    headers=next(data_reader)
    print("headers = "+ str(headers))
    
    print("\nContent")
    for line in data_reader:
        print(line)
    
    

In [ ]:
import csv
filename="tweets_noheader.csv"
with open(filename,"r")as f:
    data_reader=csv.reader(f,delimiter=',')
    
    
    print("Content")
    for line in data_reader:
        print(line)
    
    

In [ ]:
#json

import json
filename="moviereview.json"
with open(filename,"r")as f:
    a=f.read()
    movie=json.loads(a)
movie


In [ ]:
import json
filename="moviereview.json"
with open(filename,"r")as f:
    movie=json.load(f)
movie

In [ ]:
movie['Year']

In [ ]:
import json
filename="moviereviews.jsonl"
with open(filename,"r")as f:
    for  line in f:
        movie=json.loads(line)
        print(movie)

In [ ]:
#input 
a=int(input("enter the a"))
b=int(input("enter the b"))

while(b==0):
    try:
        a/b
    except:
        print("cannot divid zero")
        b=int(input("enter the b"))

c=a/b
print(c)


In [ ]:
#list comprehensions

squares=[]
for x in range(10):
    squares.append(x*x)
squares

In [ ]:
#type II
squares=[x**2 for x in range(10)]
squares

In [ ]:
#type III
squares=[x*x for x in range(10)]
squares

In [ ]:
combos=[]

for x in [1,2,3]:
    for y in [1,2,3]:
        if x!=y:
            combos.append((x,y))
            
combos

In [ ]:
combos=[(x,y) for x in [1,2,3] for y in [1,2,3]]
combos

In [ ]:
combos=[(x,y) for x in [1,2,3] for y in [1,2,3] if x!=y]
combos

In [ ]:
combos=[(x,y) for x in [1,2,3]
      for y in [1,2,3]
      if x!=y]
combos

In [ ]:
combos=[(x,y) if x!=y else (0,0)
       for x in [1,2,3]
       for y in [1,2,3]]
combos

In [ ]:
x=[111,222,333,444,555,666,777,888,999,777]
x

In [ ]:
#given number in squres and cube
import random
a=[random.randint(100,999) for _ in range(10)]
[(i,i**2,i**3)for i in a]

In [ ]:
x=int(input("enter 3 digit number:"));
print(x)
squares=[x*x]
squares
cube=[x**3]
cube
print(squares)
print(cube)

In [ ]:
#dictionaryy comprehesion
fords=("the quick brown fox jumped over the lazy dog")
tokens=fords.split(',')
tokens


In [ ]:
word_len={}


for w in tokens:
    word_len[w]=len(w)
    
word_len

In [ ]:
word_len={w:len(w) for w in words.split()}
word_len

In [ ]:
#creating generators

squares=(x*x for x in range(10))
squares

In [ ]:
for item in squares:
    print(item)

In [ ]:
#sume fundamental programming concept
#map
def f(x):
    return x*x

n=range(10)

squares=map(f,n)

print(squares)
print(list(squares))

In [ ]:
def add(a,b):
    return a+b

a=[1,2,3]
b=[2,1,4]

results=map(add,a,b)
list(results)

In [ ]:
def add(a,b):
    return a+b

a=[1,2,3]
b=[1,2,3,4]

c=map(add,a,b)
list(c)

In [ ]:
##filter
def is_even(a):
    return a%2==0

seq=range(20)

evenNumbers=filter(is_even,seq)
list(evenNumbers)

In [ ]:
In

In [ ]:
Out

In [ ]:
#magic commands
%magic

In [ ]:
%magic

In [ ]:
from random import random

l=[int(random()*10) for _ in range(0,1000)]
t=[int(random()*10) for _ in range(0,1000)]
%time print(5 in l)
%time print(5 in t)



In [ ]:
%%time
l=[10,20,30]
print(5 in l)

In [ ]:
%timeit l=[10,20,30]
print(5 in l)

In [ ]:
%precision 2
l=[(random()*10) for _ in range(0,10)]
print(l)

In [ ]:
f=open("AliceInWonderland.txt")
tokens=
tokens

## numpy

In [11]:
import numpy as np

In [12]:
import numpy as np
print(np.__version__)

1.16.2


# creating a numpy arrays

In [13]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a=np.array([1,2.2,3,4,5])
a

In [14]:
a=np.array([1,2,3,4,5])
newstrArry=a.astype(str)
newstrarry

NameError: name 'newstrarry' is not defined

In [15]:
help(a.astype)

Help on built-in function astype:

astype(...) method of numpy.ndarray instance
    a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
    
    Copy of the array, cast to a specified type.
    
    Parameters
    ----------
    dtype : str or dtype
        Typecode or data-type to which the array is cast.
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout order of the result.
        'C' means C order, 'F' means Fortran order, 'A'
        means 'F' order if all the arrays are Fortran contiguous,
        'C' order otherwise, and 'K' means as close to the
        order the array elements appear in memory as possible.
        Default is 'K'.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur. Defaults to 'unsafe'
        for backwards compatibility.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are al

In [16]:
newstrarry.tolist()

NameError: name 'newstrarry' is not defined

In [17]:
a=np.array([1,2,3,4,5],dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [18]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [19]:
##create a 1-D nupy array of 50 elements and display its contents
a=np.array(range(50))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
##write a function meta that prints the dimension ,shape and size

def meta(a):
    print(a.ndim)
    print(a.shape)
    print(a.size)
meta(a)


1
(50,)
50


# new datatype object

In [21]:
a=np.array([1,"gowri",98.2])
a

array(['1', 'gowri', '98.2'], dtype='<U11')

In [22]:
a=np.array([1,"gowri",98.2],dtype=np.object)
a

array([1, 'gowri', 98.2], dtype=object)

# can handle vectorized operations

In [23]:
l=[1,2,3,4,5]
npa=np.array(l)
l,npa

([1, 2, 3, 4, 5], array([1, 2, 3, 4, 5]))

In [24]:
l+2

TypeError: can only concatenate list (not "int") to list

In [25]:
npa+2

array([3, 4, 5, 6, 7])

# multi dimensional arrays

In [26]:
b=np.array([[1,2,3,4,5],[6,7,8,9,0]])
b

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [27]:
b.ndim, b.shape, b.size, b.dtype

(2, (2, 5), 10, dtype('int32'))

# some helpful functions

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [33]:
np.empty((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# sequence generators

In [39]:
start=10
end=100
count=10
b=np.linspace(start,end,count)
print(b)
for x in range(10,110,10):
    print(x)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
10
20
30
40
50
60
70
80
90
100


In [40]:
start=0
end=10
step=2
np.arange(start,end,step)

array([0, 2, 4, 6, 8])

In [41]:
np.random.standard_normal((2,2))

array([[-1.01129607,  2.26259399],
       [ 1.04465735, -2.08838092]])

In [42]:
a=np.random.standard_normal((2,3))
b=np.random.standard_normal((2,3))
a,b

(array([[ 0.21344149, -1.7647651 , -0.26293902],
        [-0.55637836, -0.72983757,  1.46044673]]),
 array([[-0.70266054, -0.9974183 , -0.43258187],
        [-1.46874196, -0.69485787, -0.06050657]]))

In [43]:
np.vstack([a,b])

array([[ 0.21344149, -1.7647651 , -0.26293902],
       [-0.55637836, -0.72983757,  1.46044673],
       [-0.70266054, -0.9974183 , -0.43258187],
       [-1.46874196, -0.69485787, -0.06050657]])

In [44]:
a.transpose()
a

array([[ 0.21344149, -1.7647651 , -0.26293902],
       [-0.55637836, -0.72983757,  1.46044673]])

In [45]:
np.save('myfirstarray.npy',a)

In [ ]:
al=np.load('myfirstarray.npy')
al

In [ ]:
a=[[1,2],[5,6]]
b=[[1,0],[0,1]]
np.dot(a,b)

In [ ]:
import numpy as np


In [ ]:
a=np.array(range(1,11))
b=np.array(range(2001,2011))
a,b

In [ ]:
a=np.zeros((3,3))
for row in range(3):
    for col in range(3):
        if(row==col):
            a[row][col]=1
        print(row,col,a[row][col])
a

In [ ]:
##### input from user
row=int(input("enter the row"))
col=int(input("enter the col"))
b=np.empty((row,col))

for i in range(row):
    for j in range(col):
        b[i][j]=int(input("enter the row,col value"))
b

In [ ]:
#add two matrix
a=np.array([range(5),range(5,10),range(10,15),range(15,20)])
a

# indexing and slicing

In [ ]:
v=np.linspace(0,10,5)
v

In [ ]:
v[0],v[1],v[-1]

In [ ]:
v[2:4]

In [ ]:
vv=np.random.random((5,5))
vv*10

In [ ]:
vv[0][0]

In [ ]:
vv[0,0],vv[4,3]

In [ ]:
l1=[[1,2,3],[4,5,6]]
l1[0][1]

In [ ]:
vv

In [ ]:
vv[2:5,1]

In [ ]:
vv[2:5,0:3]

In [ ]:
print(v)
v2=v[2:4]
print(v2)
v2[0]=55
print(v,v2)

In [ ]:
print(v)
v2=v[2:4].copy()
print(v2)
v2[0]=22
print(v,v2)


# filtering data

In [ ]:
print(v)
v1=v[[1,2,3]]
print(v1)

In [ ]:
v>1

In [ ]:
bool_ind=v>5

In [ ]:
v[bool_ind]

In [ ]:
print(vv)
vv[vv>.5]

In [ ]:
vv[vv>.5]=1
vv

In [ ]:
vals=np.arange(10)
#vals=np.array([1,3,5,7,9])
print(vals)
np.where(vals%3==0)

In [ ]:
vals_new=np.where(vals%2==0,-1,vals)
vals_new

In [ ]:
data=np.array([range(5),range(5,10),range(10,15),range(15,20)])
data

# HW

In [ ]:
##two input from user
row=int(input("enter the row"))
col=int(input("enter the col"))
b=np.empty((row,col))

for i in range(row):
    for j in range(col):
        b[i][j]=int(input("enter the row,col value"))
row=int(input("enter the row"))
col=int(input("enter the col"))
a=np.empty((row,col))

for i in range(row):
    for j in range(col):
        b[i][j]=int(input("enter the row,col value"))
a,b

In [ ]:
import numpy as np

In [ ]:
a=data[(data%2!=0)]
b=np.where(data%3==0,-1,data)
a,b

In [ ]:
#add two matrix
a=np.array([range(5),range(5,10),range(10,15),range(15,20)])
b=np.array([range(4),range(4,8),range(8,12),range(12,16),range(16,20)])
print(a,"=a")
print(b,"=b")
c=a.transpose()
print(c,"=c")
d=c.transpose()
print(d,"=d")
e=d==a
print(e)

In [ ]:
r=np.arange(0,100,3)
r[(r%2==0) | (r%9==0)] #multiple 2 and 9
#r[(r%2==0) & (r%9==0)]only multiple 2 and 9

r

In [ ]:
import csv

temp=[]

f="weather1week.csv"
with open(f,"r")as f:
    a=csv.reader(f,delimiter=';')

    print("start")
    for line in a:
       # print(line[5])
        temp.append(line[5])
temp
b=np.array([temp],dtype=float)
b  
f=b*(9/5)+32
f


In [ ]:
##age list and year
age=np.array([10,20,30,40,50,60,70,80,90,11])
for year in range(2010,2021):
    age=age+1
age

In [ ]:
##5x5 matrix largest number and smallest number
a=np.random.random((5,5))
a=a*10
a
n=a.astype(int)
n
x=n.max()
y=n.min()
print(x)
print(y)


In [ ]:
##create a numpy array of marks
a=np.random.randint(500,1200,size=20)
a
b=(a*100)/1200
print(b)
c=b.max()
print("first mark",c)
d=b.min()
print("last mark",d)

In [ ]:
#creat a numpy array 50 random elements
a=np.random.randint(50,size=50)
a
v=a.min()
print(v)
m=a.max()
print(m)
b=(a-v)/(m-v)
b
print("normalized value",b)

In [ ]:
##read the week file and find the average and hotter and cold 
import csv
temp=[]
f="weather1week.csv"
with open(f,"r")as f:
    r=csv.reader(f,delimiter=";")
    print("start")
    for line in r:

        temp.append(float(line[5]))
temp
a=np.array([temp])
b=np.mean(a)
print("average temperature",b)
c=a.max()
print("hottest temperature",c)
d=a.min()
print("coldest temperature",d)
e=a(a%24.19791)
e


In [ ]:
##reverse the string

a=input("enter the name")
print(a)


# some additional snippets

In [ ]:
import numpy as np
data=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float)
data

In [ ]:
data[:,1:4]

In [ ]:
data[::-1]

In [ ]:
data[:,::-1]

In [ ]:
data[::-1,::-1]

In [ ]:
data[0,0]=np.inf
data[-1,-1]=np.nan
data

In [ ]:
#reshaping
reshaped=data.reshape((5,2))
reshaped

In [ ]:
flattened=data.flatten()
flattened

In [ ]:
#random numbers
np.random.rand(3,3)


In [ ]:
np.random.randint(0,10,(5,5))

In [ ]:
np.random.choice(['India','China','Australia','Canada','France'],(3,4))

In [ ]:
np.random.seed(5)
np.random.choice(['India','China','Australia','Canada','France'],(3,4))

In [ ]:
#consider the set of students
names=["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o"]
chess=np.random.choice(["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o"],(10,5))
print("chess=",chess)


# vectorize

In [ ]:
def calc(a):
        if a%2==0:
            return a**2
        else:
            return a-1

In [ ]:
vals=np.array([1,2,3,4,5])
calc(vals[0])

In [ ]:
calc(vals)

In [ ]:
v_calc=np.vectorize(calc)
v_calc(vals)

In [ ]:
b=np.array([1,2,3,4,5])
bin(b[3])

In [ ]:
v_bin=np.vectorize(bin)
v_bin(b)

# records-using heterogeneous datatypes

In [ ]:
rec=np.array([(1,(95.5,98),'ram'),(2,(100,96.5),'raj')],dtype=[('rollno',np.int32),('marks',np.float16,2),('names',np.str,4)])

In [ ]:
rec

In [ ]:
rec['names']

In [ ]:
rec[0]

In [ ]:
rec['names']

In [ ]:
rec[0]['marks']

In [ ]:
rec['marks'][0]

In [ ]:
schems=np.dtype([('year',np.float16),
                ('month',np.float16),
                ('day',np.float16),
                ('hour',np.float16),
                ('minute',np.float16),
                 ('temp',np.float16)])
np_data=np.loadtxt('weather1week.csv',dtype=schems,delimiter=';')
np_data

In [ ]:
np_data[0]

In [ ]:
np_data['temp']

In [ ]:
np_data['temp']=np_data['temp']*(9/5)+32
np_data

In [ ]:
schems=np.dtype([('year',np.float16),
                 ('month',np.float16),
                 ('day',np.float16),
                 ('hour',np.float16),
                 ('minute',np.float16),
                 ('temp',np.float16),
                 ('temp1',np.float16)])
np_data=np.loadtxt('weatherComp.csv',dtype=schems,delimiter=';')
np_data
                 

In [ ]:
a=np_data['temp'].max()
print(a)
b=np_data['temp1'].max()
print(b)
if(a>b):
    print(a,"2017 is hot")
else:
    print(b,"2018 is hot")

In [ ]:
#create a array 100 elements 
a=np.linspace(1,100,num=100,dtype=int)
print('a=',a)

b=a.reshape((4,25))
print('b=',b)


# pandas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
schema=np.dtype([('sepal_length',np.float16),('sepal_width',np.float16),('petal_length',np.float16),('petal_width',np.float16),
                ('species','<U16')])


In [ ]:
np_data=np.loadtxt('iris.csv',dtype=schema,delimiter=',')
np_data

In [ ]:
np_data[0]

In [ ]:
np_data['species']

In [ ]:
pd_data=pd.read_csv('iris.csv')
pd_data.head()

In [ ]:
pd_data=pd.read_csv('iris.csv',names=['sepal_length','sepal_width','petal_length','petal_width','species'])
pd_data.head()

In [ ]:
pd_data.sepal_length

In [ ]:
pd_data=pd.read_csv('iris.csv',usecols=[0,1,4],names=['sepal_length','sepal_width','species'])
pd_data.head()
#you have header in your file d'not use names

In [ ]:
pd_data.shape

In [ ]:
pd_data.dtypes

In [ ]:
pd_data.get_dtype_counts()

In [ ]:
pd_data.isnull().values.any()

In [ ]:
pd_csv=pd.read_csv('tweets_withHeader.csv')
pd_csv.head()

In [ ]:
pd_csv=pd.read_csv('tweets_noHeader.csv',names=['id','polarity','text'])
pd_csv.head()

In [ ]:
pd_w=pd.read_csv('weather1week.csv',names=['year','month','day','hours','mini','temp'],delimiter=';')
pd_w.head()

# pandas

In [ ]:
import pandas as pd
print(pd.__version__)

In [ ]:
s=pd.Series([0,1,4,9,16,25],name='squares')
s

In [ ]:
s.values

In [ ]:
s.index

In [ ]:
s[2]

In [ ]:
s[1:4]

# creating DataFrames

In [ ]:
mat=np.arange(0,9).reshape(3,3)
mat

In [ ]:
pd.DataFrame(mat)

In [ ]:
arr=[(1,'a'),(2,'b'),(3,'b')]
pd.DataFrame(arr,columns=['Numbers','Letters'])

In [ ]:
dictDf={'Numbers':[1,2,3],'Letters':['a','b','c']}
pd.DataFrame(dictDf)

In [ ]:
dictDf={'Numbers':[1,2,3,4],'Letters':['a','b','c']}
pd.DataFrame(dictDf)

In [ ]:
ser1=pd.Series([24,30,10,23,32,60],name='age')
ser2=pd.Series(['ram','raj','gowri','shankar'],name='name')
pd.DataFrame({"age":ser1,"name":ser2})

In [ ]:
pd.DataFrame([ser1,ser2])

In [ ]:
pd.DataFrame([ser1,ser2]).T

In [ ]:
a=[2,4,6,8,10]
pd.DataFrame(a)

In [ ]:
s1=pd.Series(['sivaji','kgf','kabali','bagubali','ranimurugan'],name='Moviesnames')
s2=pd.Series(['rajini','yash','rajini','birabas','sivakarthikavayan'],name='lead male')
s3=pd.Series(['aasin','--------','abx','aanuska','karithisuresh'],name='lead female')
s4=pd.Series(['1','1','1','1','1'],name='remark')
pd.DataFrame([s1,s2,s3,s4]).T

In [ ]:
age=pd.DataFrame([ser1,ser2]).T
age

In [ ]:
age['app_range']=[1 if a<=15 else 2 if 15<a<50 else 3 for a in age['age']]
age

In [ ]:
age.append(pd.DataFrame({'age':pd.Series(31),'name':pd.Series('GOWRI'),'age_range':pd.Series(2)}))



In [ ]:
a=[2,4,6,8,10,12]
pd.DataFrame(a)

In [ ]:
a['3m']=[1 if b/3 else 0 for b in a['a']]
a