In [2]:
import pandas as pd
import numpy as np
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error
#df['holiday'].unique()

In [41]:
df=pd.read_csv("train_METRO.csv")
df['date']=pd.to_datetime(df['Date']).dt.day
df['month']=pd.to_datetime(df['Date']).dt.month
df['hour']=pd.to_datetime(df['Time']).dt.hour

df['is_monthstart']=pd.to_datetime(df['date_time']).dt.is_month_start
df['is_monthend']=pd.to_datetime(df['date_time']).dt.is_month_end
df['Weekday_Name']=pd.to_datetime(df['date_time']).dt.weekday_name
df['Week_end']=df['Weekday_Name'].apply(lambda x:1 if x=='Saturday' or x=="Sunday" else 0)

df['temp']=df['temp']-273.15

del df['Unnamed: 0']
del df['Date']
del df['date_time']
del df['weather_description']
del df['rain_1h']
del df['snow_1h']
del df['Year']
del df['Time']

df['is_E_M']=df['hour'].apply(lambda x:1 if x>=3 and x>=6 else 0)
df['is_M']=df['hour'].apply(lambda x:1 if x>=7 and x>=11 else 0)
df['is_A_N']=df['hour'].apply(lambda x:1 if x>=12 and x>=15 else 0)
df['is_E']=df['hour'].apply(lambda x:1 if x>=15 and x>=19 else 0)
df['is_N']=df['hour'].apply(lambda x:1 if x>=19 and x>=23 else 0)
df['is_M_N']=df['hour'].apply(lambda x:1 if x>=23 and x>=2 else 0)
f_df=pd.get_dummies(df, columns=['weather_main','holiday','Weekday_Name','is_monthstart','is_monthend'])

del f_df['traffic_volume']
x=f_df.as_matrix()
y=df['traffic_volume'].as_matrix()

x,y
#df.head()

C:\Users\gowri\Anaconda3\lib\site-packages\ipykernel_launcher.py:31: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
C:\Users\gowri\Anaconda3\lib\site-packages\ipykernel_launcher.py:32: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


(array([[15.13, 40.  ,  2.  , ...,  0.  ,  1.  ,  0.  ],
        [16.21, 75.  ,  2.  , ...,  0.  ,  1.  ,  0.  ],
        [16.43, 90.  ,  2.  , ...,  0.  ,  1.  ,  0.  ],
        ...,
        [-4.93, 90.  , 31.  , ...,  0.  ,  0.  ,  1.  ],
        [-4.25, 75.  , 31.  , ...,  0.  ,  0.  ,  1.  ],
        [-3.67, 90.  , 31.  , ...,  0.  ,  0.  ,  1.  ]]),
 array([5545, 4516, 4767, ..., 2921, 2557, 1857], dtype=int64))

In [1]:
#Winter in New York City
#January in NYC | February in NYC | March in NYC
#Spring in New York City
#April in NYC | May in NYC | June in NYC
#Summer in the City Guide
#June in NYC | July in NYC | August in NYC
#Fall in NYC
#September in NYC | October in NYC | November in NYC
df['month']
df['is_winiter']=df['month'].apply(lambda x=1 if x>=1 and x>=3 else 0 )
df['is_winiter']
#df[(df['month']==1)]

SyntaxError: invalid syntax (<ipython-input-1-41fa34c1f580>, line 10)

In [15]:
a=df.loc[:,"traffic_volume"].mean()
b=df.loc[:,"traffic_volume"].median()
c=df.loc[:,"traffic_volume"].mode()

a,b,c

(3230.8092748735244, 3313.5, 0    356
 dtype: int64)

In [42]:
model = ensemble.GradientBoostingRegressor(
    n_estimators=1000,
    learning_rate=0.1,
    max_depth=6,
    min_samples_leaf=9,
    max_features=0.1,
    loss='huber',
    random_state=0
)
model.fit(x,y)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='huber', max_depth=6,
             max_features=0.1, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=9, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=1000,
             n_iter_no_change=None, presort='auto', random_state=0,
             subsample=1.0, tol=0.0001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [43]:
#test
df1=pd.read_csv("test_METRO.csv")

df1['date']=pd.to_datetime(df1['Date']).dt.day
df1['month']=pd.to_datetime(df1['Date']).dt.month
df1['hour']=pd.to_datetime(df1['Time']).dt.hour

df1['is_monthstart']=pd.to_datetime(df1['date_time']).dt.is_month_start
df1['is_monthend']=pd.to_datetime(df1['date_time']).dt.is_month_end
df1['Weekday_Name']=pd.to_datetime(df1['date_time']).dt.weekday_name
df1['Week_end']=df1['Weekday_Name'].apply(lambda x:1 if x=='Saturday' or x=="Sunday" else 0)

df1['temp']=df1['temp']-273.15

del df1['Unnamed: 0']
del df1['rain_1h']
del df1['snow_1h']
del df1['date_time']
del df1['weather_description']
del df1['Time']
del df1['Date']
df1['is_E_M']=df1['hour'].apply(lambda x:1 if x>=3 and x>=6 else 0)
df1['is_M']=df1['hour'].apply(lambda x:1 if x>=7 and x>=11 else 0)
df1['is_A_N']=df1['hour'].apply(lambda x:1 if x>=12 and x>=15 else 0)
df1['is_E']=df1['hour'].apply(lambda x:1 if x>=15 and x>=19 else 0)
df1['is_N']=df1['hour'].apply(lambda x:1 if x>=19 and x>=23 else 0)
df1['is_M_N']=df1['hour'].apply(lambda x:1 if x>=23 and x>=2 else 0)


f_df1=pd.get_dummies(df1, columns=['weather_main','holiday','Weekday_Name','is_monthstart','is_monthend'])

x1=f_df1.as_matrix()
y1=df1['traffic_volume'].as_matrix()

x1,y1

C:\Users\gowri\Anaconda3\lib\site-packages\ipykernel_launcher.py:32: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
C:\Users\gowri\Anaconda3\lib\site-packages\ipykernel_launcher.py:33: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


(array([[-3.400e+00,  7.500e+01,  1.848e+03, ...,  1.000e+00,  1.000e+00,
          0.000e+00],
        [-3.200e+00,  1.000e+00,  1.806e+03, ...,  1.000e+00,  1.000e+00,
          0.000e+00],
        [-3.400e+00,  1.000e+00,  1.211e+03, ...,  1.000e+00,  1.000e+00,
          0.000e+00],
        ...,
        [ 9.580e+00,  9.000e+01,  2.159e+03, ...,  0.000e+00,  0.000e+00,
          1.000e+00],
        [ 8.940e+00,  9.000e+01,  1.450e+03, ...,  0.000e+00,  0.000e+00,
          1.000e+00],
        [ 8.970e+00,  9.000e+01,  9.540e+02, ...,  0.000e+00,  0.000e+00,
          1.000e+00]]),
 array([1848, 1806, 1211, ..., 2159, 1450,  954], dtype=int64))

In [44]:
model1 = ensemble.GradientBoostingRegressor(
    n_estimators=1000,
    learning_rate=0.1,
    max_depth=6,
    min_samples_leaf=9,
    max_features=0.1,
    loss='huber',
    random_state=0
)
model1.fit(x1,y1)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='huber', max_depth=6,
             max_features=0.1, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=9, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=1000,
             n_iter_no_change=None, presort='auto', random_state=0,
             subsample=1.0, tol=0.0001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [45]:
# Find the error rate on the training set
mae = mean_absolute_error(y, model.predict(x))
print("Training Set Mean Absolute Error: %.4f" % mae)

# Find the error rate on the test set
mae = mean_absolute_error(y1, model1.predict(x1))
print("Test Set Mean Absolute Error: %.4f" % mae)


Training Set Mean Absolute Error: 208.8415
Test Set Mean Absolute Error: 35.1282


In [ ]:
from sklearn.ensemble import RandomForestRegressor

reg = RandomForestRegressor()
reg.fit(x,y)
pred=reg.predict(x1)
mse = mean_absolute_error(y1,pred)
print("Mean Absolute Error : %.4f" % mse)